---
title: "Diversity/Compositional Analysis"
author: "Yining Sun"
date: "`r format(Sys.time(), '%B %d %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
    highlight: tango
editor_options: 
  chunk_output_type: console
---

# Load packages
```{r start}

# be in the right place
setwd("/local/workdir/ys636/BIOMI6300-Project2")

# efficiently load packages
pacman::p_load(phyloseq, iNEXT, ggpubr, tidyverse, install = FALSE)

# load functions and color preferences
source("/local/workdir/ys636/BIOMI6300-Project2/code/functions.R")
source("/local/workdir/ys636/BIOMI6300-Project2/code/colors_and_shapes.R")
```


# Load data
```{r load-data}
load("/local/workdir/ys636/BIOMI6300-Project2/data/preprocessed_physeq.RData")

noMitoChloroCJMock_physeq

### I gave the name of "preprocessed_physeq" to the S4 object called "noMitoChloroCJMock_physeq".
### So here I should call noMitoChloroCJMock_physeq instead of preprocessed_physeq.

```


# Run biodiversity analysis
## work with the iNEXT packages
```{r iNEXT-div-estimation}
# prepare data for iNEXT
iNEXT_input_df <-
  noMitoChloroCJMock_physeq %>%
  otu_table() %>%
  data.frame()

# run iNEXT on the data
# calculate diversity with iNEXT
set.seed(0402)


iNEXT_data <- iNEXT(iNEXT_input_df, q = c(0, 1, 2), datatype = "abundance")
save(iNEXT_data, file = "/local/workdir/ys636/BIOMI6300-Project2/data/iNEXT_biodiv_analysis.RData")



load("/local/workdir/ys636/BIOMI6300-Project2/data/iNEXT_biodiv_analysis.RData")
# note: the obkect is called "iNEXT_data"
str(iNEXT_data)
typeof(iNEXT_data) # list


# make workable df
div_iNEXT_df <-
  iNEXT_data$AsyEst %>%
  dplyr::rename(names = Assemblage)
  
div_iNEXT_df$source <- substr(div_iNEXT_df$names, 13,16)


View(div_iNEXT_df)

### This latest df already has "source" column,
### everything looks good so far!
  
```



# Generate rarefaciton plot
```{r}

###
# Prepare data to color the figure for iNEXT
dat <- colnames(iNEXT_input_df) %>%    
  data.frame() 

colnames(dat)[1] <- "names"     

sub_metadata <- dat %>% 
  make_MA2_metadata()

# Add the colors for the plotting!
dat_iNEXT <- dat %>%      
  left_join(sub_metadata, by = "names") %>%    
  mutate(fraction_color = ifelse(source == "dair", "goldenrod1",                                  ifelse(source == "meat", "firebrick3",         "blue")))


# Now plot it all :) 
# Plot the rarefaction/extrapolation curve (type = 1)
rarefaction_fixed_plot <-   ggiNEXT(iNEXT_data, type=1, facet.var="Order.q") +   
  facet_wrap(~Order.q, scales="fixed") +  
  scale_color_manual(values = dat_iNEXT$fraction_color,  guide = FALSE) +  
  scale_fill_manual(values = dat_iNEXT$fraction_color, guide = FALSE) +  
  theme(legend.position = "none") +   
  labs(x = "Number of Sequences") 

rarefaction_fixed_plot

```


# Completeness curve
```{r completeness-curve}
ggiNEXT(iNEXT_data, type = 2) + 
  scale_color_manual(values = dat_iNEXT$fraction_color,  guide = FALSE) +  
  scale_fill_manual(values = dat_iNEXT$fraction_color, guide = FALSE) +  
  theme(legend.position = "none") 

```


# Make boxplot of diversity
```{r boxplot-div}

iNEXT_data$AsyEst %>%
  head()

# look into the observed diversity values and check them
obs_rich_df <-
  iNEXT_data$iNextEst$size_based %>%
  # extract the richness from the data
  dplyr::filter(Order.q == 0) %>%
  dplyr::filter(Method == "Observed") %>%
  dplyr::rename(names = Assemblage) %>%
  make_MA_metadata()
 

ggboxplot(obs_rich_df, x = "source", y = "qD", 
          color = "source", palette = c("#00AFBB", "#E7B800"),
          ylab = "qD", xlab = "source",
          )


# look into the rarefaction diversity values and check them

rf_rich_df <-
  iNEXT_data$iNextEst$size_based %>%
  # extract the richness from the data
  dplyr::filter(Order.q == 0) %>%
  dplyr::filter(Method == "Rarefaction") %>%
  dplyr::rename(names = Assemblage) %>%
  make_MA_metadata()

ggboxplot(rf_rich_df, x = "source", y = "qD", 
          color = "source", palette = c("#00AFBB", "#E7B800"),
          ylab = "qD", xlab = "source",
          )



# Wilcoxon test for observed richness
res1 <- wilcox.test(qD ~ source, data = obs_rich_df,
                   exact = FALSE)
res1

# Wilcoxon test for rarefied richness
res2 <- wilcox.test(qD ~ source, data = rf_rich_df,
                   exact = FALSE)
res2

```


# Session information
```{r session_info}
devtools::session_info()
```
