---
title: "Compositional Analysis"
author: "Yining Sun"
date: "2023-04-27"
output: html_document
editor_options: 
  chunk_output_type: console
---

# load packages
```{r}
# efficiently load packages
pacman::p_load(phyloseq, iNEXT, ggpubr, tidyverse, vegan, install = FALSE)
# be in the right place
setwd("/local/workdir/ys636/BIOMI6300-Project2")
# load functions and color preferences
source("/local/workdir/ys636/BIOMI6300-Project2/code/functions.R")
source("/local/workdir/ys636/BIOMI6300-Project2/code/colors_and_shapes.R")
```



# load data
```{r load-data}
load("/local/workdir/ys636/BIOMI6300-Project2/data/preprocessed_physeq.RData")
noMitoChloroCJMock_physeq

# what are the sample size distributions?
noMitoChloroCJMock_physeq %>%
  # prune_samples(sample_sum(.) > 2000, .) %>%
  sample_sums() %>%
  data.frame() %>%
  View()

# Probably not remove any samples since I only have 16 samples and they have similar number of reads
```


# normalize the reads
## scale the read counts
```{r scale-reads}
set.seed(2000)

# scale the reads using function scale_reads from functions.R

# intuition check of number of seqeunces per sample
min(sample_sums(noMitoChloroCJMock_physeq)) ### 4186, correct!

scaled_seqs <-  
  noMitoChloroCJMock_physeq %>%
  scale_reads(round = "matround")

# Now check the sequencing depth! 
scaled_seqSums_df <-   
scaled_seqs %>%  
otu_table(.) %>%  # Take the sum of the sample abundance   
colSums(.) %>%  
data.frame() %>%  
rownames_to_column(., var = "names") %>% 
 make_MA_metadata()
 
 # Rename the 2nd column 
 colnames(scaled_seqSums_df)[2] <- "TotalSeqs"   
 
 # Plot the histogram
 scaled_seqSums_df %>%  
 ggplot(aes(x=TotalSeqs)) + #fill = fraction   
 ggtitle("Histogram of Raw Read Counts Samples") +  
 geom_histogram(bins = 16) + 
 theme(legend.position = c(0.15, 0.85))   

### i removed the   


```


# PCoA
```{r}
# calculate Bray-curtis Dissimilarity
scaled_BC_pcoa <-
  ordinate(
    physeq = scaled_seqs,
    method = "PCoA",
    distance = "bray",
    binary = FALSE
  )

View(scaled_BC_pcoa)
# ordiate measures some distance



# plot the PCoA

plot_ordination(
  physeq = scaled_seqs, 
  ordination = scaled_BC_pcoa,
  color = "source",
  shape = "source",
  title = "Scaled Bray-Curtis PCoA") +
  geom_point(size = 5, alpha = 0.5, aes(color = source)) +
  scale_color_manual(values = source_colors)


## both x-axis and y-axis represent eigen values

```


# stats
# check for difference in the cummunities using PERMANOVA
```{r permanova}
# calculate bray curtis for permanova
scaled_source <- phyloseq::distance(scaled_seqs, method = "bray", binary = FALSE)

# pull out metadata
metadata <- noMitoChloroCJMock_physeq %>%
  sample_data() %>%
  data.frame()


# permutational multivariate analysis of variance using distance matrices
# aka PERMANOVA using the adonis2 function form vegan
# test the hypothesis that the fraction centroids are different using the bray curtis
# test if the centroids of the fractions are different
adonis2(scaled_source ~ source, data = metadata)



```


# homogeniety of dispersion test: beta disper
```{r}
# dispersion between stations
betadispr_source <- betadisper(scaled_source, metadata$source)
permutest((betadispr_source))

```



# compositional analysis
```{r}
phylum_df <- 
  scaled_seqs %>%
  tax_glom(taxrank = "Phylum") %>% # agglomerate/merge counts by phylum
  transform_sample_counts(function(x) {x/sum(x)}) %>% # transform to relative abundances
  psmelt() %>%         # melt into long format dataframe
  dplyr::filter(Abundance > 0.01)    # filter out phyla that are > 1% abundant
       
# plot the phylum distributions
phylum_df %>%
  # dplyr::filter(depth == "S") %>%
  ggplot(aes(x = source, y = Abundance, fill = Phylum)) +
  geom_bar(stat = "identity", color = "gray") +
  # facet_grid(~source) +
  scale_fill_manual(values = phylum_colors)


```


