---
title: "DADA2 Workflow"
author: "Yining Sun"
date: "2023-04-17"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Let's atrat! Sew workdiir, source code and load packages!
```{r prep-to-start}
# be in the right place
setwd("/local/workdir/ys636/BIOMI6300-Project2")

# source functions.R
source("/local/workdir/ys636/BIOMI6300-Project2/code/functions.R")

# load packages with pacman
pacman::p_load(dada2, tidyverse, phyloseq, patchwork, Biostrings, install = FALSE)

# check dada2 version
packageVersion("dada2")
```


# Set path
```{r set-path}

# set paths for meat and dairy folders of gzipped files
path_meat <- ("/local/workdir/ys636/BIOMI6300-Project2/data/meat")
path_dairy <- ("/local/workdir/ys636/BIOMI6300-Project2/data/dairy")

# check path
list.files(path_meat)  # 16 fastq.gz files, looks good!
list.files(path_dairy)  # 16 fastq.gz files, looks good, too!

```

# Create variables for forward and reverse reads
```{r F-and-R-variables}
#R1 is forward, R2 is reverse

# F and R variables for MEAT group
F_reads_meat <- sort(list.files(path_meat, pattern = "_1.fastq.gz",
                                 full.names = TRUE))

R_reads_meat <- sort(list.files(path_meat, pattern = "_2.fastq.gz",
                                 full.names = TRUE))

# F and R variables for Dairy group
F_reads_dairy <- sort(list.files(path_dairy, pattern = "_1.fastq.gz",
                                 full.names = TRUE))

R_reads_dairy <- sort(list.files(path_dairy, pattern = "_2.fastq.gz",
                                 full.names = TRUE))
```


# Quality plot of raw reads
```{r QualPlot-untrimmed}
# show the quality of each base on the reads of all the 8 samples in both groups

# Meat group
## Forward
F_Qual_plot_meat <- plotQualityProfile(F_reads_meat)
F_Qual_plot_meat                      ### The first 190-200 bases had quality scores over 20
## Reverse
R_Qual_plot_meat <- plotQualityProfile(R_reads_meat)
R_Qual_plot_meat                      ### The first 160 bases had quality scores over 20

# Dairy group
## Forward
F_Qual_plot_dairy <- plotQualityProfile(F_reads_dairy)
F_Qual_plot_dairy             
### The last 4 samples' first 200-210 bases had quality scores over 20, the first 4 samppels looked good with all reads

## Reverse
R_Qual_plot_dairy <- plotQualityProfile(R_reads_dairy)
R_Qual_plot_dairy             
### The last 4 samples' first 160 bases had quality scores over 20, the first 4 samppels looked good with all reads

### based on the quality plots of all the 16 samples from both groups, I decided to set the quality score cutoff as 20, rather than 30.

```


# Modify file names for the forward and reverse filtered reads
```{r variables-trimmed-reads}

# Create characters for trimmed reads 
sample_meat <- scan(file = "/local/workdir/ys636/BIOMI6300-Project2/data/meat.txt", what = "character")
sample_meat

sample_dairy <- scan(file = "/local/workdir/ys636/BIOMI6300-Project2/data/dairy.txt", what = "character")
sample_dairy

# create variables to hold file names
## Meat group
filtered_F_reads_meat <- file.path(path_meat, "filtered", paste0(sample_meat, "_1.fastq.gz"))
filtered_R_reads_meat <- file.path(path_meat, "filtered", paste0(sample_meat, "_2.fastq.gz"))

## Dairy group
filtered_F_reads_dairy <- file.path(path_dairy, "filtered", paste0(sample_dairy, "_1.fastq.gz"))
filtered_R_reads_dairy <- file.path(path_dairy, "filtered", paste0(sample_dairy, "_2.fastq.gz"))

```


# Filter and trim the raw reads!!
```{r filter-and-trim}

# Meat group
filtered_out_meat <- filterAndTrim(F_reads_meat, filtered_F_reads_meat, 
                              R_reads_meat, filtered_R_reads_meat,
                              trimRight = c(90, 100),
                              maxN = 0, maxEE = c(1,1), truncQ = 2, 
                              rm.phix = TRUE, compress = TRUE, 
                              multithread = TRUE)
## kept the first 200-210 bases


# Dairy group
filtered_out_dairy <- filterAndTrim(F_reads_dairy, filtered_F_reads_dairy, 
                              R_reads_dairy, filtered_R_reads_dairy,
                              trimRight = c(100, 110),
                              maxN = 0, maxEE = c(1,1), truncQ = 2, 
                              rm.phix = TRUE, compress = TRUE, 
                              multithread = TRUE)
## kept the first 190-200 bases


```


