---
title: "Phyloseq_PreProcessing"
author: "Yining Sun"
date: "`r format(Sys.time(), '%B %d %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
    highlight: tango
editor_options: 
  chunk_output_type: console
---

# Prepare to start the preprocessing
```{r start-prep}
#Be in the right place
setwd("/local/workdir/ys636/BIOMI6300-Project2")

# load packages
pacman::p_load(tidyverse, phyloseq, install = FALSE)

# source functions
source("/local/workdir/ys636/BIOMI6300-Project2/code/functions.R")
source("/local/workdir/ys636/BIOMI6300-Project2/code/colors_and_shapes.R")

```


# Load the data
```{r load-data}

# load in the raw_physeq data from DADA2 Practice.Rmd
load("/local/workdir/ys636/BIOMI6300-Project2/data/raw_physeq.RData")

# Take a look at the S4 object
raw_phyloseq

# Tell us about your phyloseq
str(raw_phyloseq)
typeof(raw_phyloseq)

View(raw_phyloseq@otu_table)
View(raw_phyloseq@tax_table)
View(data.frame(sample_data(raw_phyloseq)))

```


# Remove unnecessary taxa
```{r rm-ASVs}

# 1. Mitochondria ASVs
# 2. Chloroplast ASVs
# Note: since I don't have controls or mock community, I will skip removing this two types of ASV data.

test_physeq <-
  raw_phyloseq %>% 
   ## remove the mitochondria ASVs
  subset_taxa(Family != "Mitochondria") %>%
   ## remove the chloroplast ASVs
  subset_taxa(Order != "Chloroplast")

noMitoChloroCJMock_physeq <- 
  raw_phyloseq %>%
  subset_taxa(Family != "Mitochondria" | is.na(Family)) %>%
  subset_taxa(Order != "Chloroplast" | is.na(Order)) %>%
  prune_samples((sample_names(.)) %!in% c("CJ-V08-P", "MockZyomPos"), .) %>%
  # now we will remove any ASVs of count 0
  prune_taxa(taxa_sums(.) > 0, .)
  

noMitoChloroCJMock_physeq


# how many taxa have we removed so far?
num_ASVs_rm <- ntaxa(raw_phyloseq) - ntaxa(noMitoChloroCJMock_physeq) ## 0
# proportion
prop_ASVs_rm <- ntaxa(raw_phyloseq)/ntaxa(noMitoChloroCJMock_physeq)  ## 1

### after this step, there is no taxa removed
### which means there is no mitochondria or chloroplast ASVs in the samples

```


